pipeline {
    agent any

    stages {
      stage ('Clean workspace') {
        steps {
          cleanWs()
        }
      }
      stage ('Git Checkout') {
        steps {
            git branch: 'main',  credentialsId:'f3de8d23-ae66-427f-a339-50df0a740664',url: 'git@github.com:marimain/mvc-core7.git'
          }
      }
      stage('Restore packages') {
        steps {
            bat 'dotnet build C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\mvc-core7\\mvc-core7.sln /p:DeployOnBuild=true  /P:DeployIISAppPath=C:\\WebSites\\MVCCoreJenkins --configuration Release'
            zip archive: true, dir: '', overwrite: true, zipFile: 'mvc-core7.zip'
          }
      } //build
    stage('Deploy Stage') {
                steps {
                    bat 'net stop "w3svc"'
                    bat '"C:\\Program Files (x86)\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe" -verb:sync -source:package="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\mvc-core7\\mvc-core7.zip" -dest:auto -setParam:"IIS Web Application Name"="MVCCoreJenkins" -skip:objectName=filePath,absolutePath="C:\\WebSites\\MVCCoreJenkins" -enableRule:DoNotDelete -allowUntrusted=true'
                    bat 'net start "w3svc"'
                }
            }

    }// stages
}
